name: .NET Build Test (API Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Verifica tu versión

      # Restaura SOLO el proyecto principal (asumiendo que está en la raíz)
      - name: Restore Main API Project Dependencies
        run: dotnet restore TaskFlowApi.csproj

      # Compila SOLO el proyecto principal (asumiendo que está en la raíz)
      - name: Build Main API Project
        run: dotnet build TaskFlowApi.csproj --configuration Release --no-restore

      # --- ¡Hemos quitado el paso de ejecutar pruebas por ahora! ---
