# Nombre del flujo de trabajo
name: .NET Build and Test (Flat Structure)

# Disparadores
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar código
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 2. Configurar .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Verifica tu versión

      # 3. Restaurar dependencias PARA CADA PROYECTO
      #    Como no usamos el .sln, restauramos por separado
      - name: Restore Main API Project
        run: dotnet restore TaskFlowApi.csproj # Asume que está en la raíz

      - name: Restore Test Project
        run: dotnet restore TaskFlowApi.Tests.csproj # Asume que está en la raíz

      # 4. Compilar CADA PROYECTO por separado
      - name: Build Main API Project
        run: dotnet build TaskFlowApi.csproj --configuration Release --no-restore

      - name: Build Test Project
        run: dotnet build TaskFlowApi.Tests.csproj --configuration Release --no-restore

      # 5. Ejecutar pruebas (apuntando al proyecto de pruebas)
      - name: Run unit tests
        run: dotnet test TaskFlowApi.Tests.csproj --configuration Release --no-build --verbosity normal
